### ISSUE TITLE
Check 'targetDependencies' for greentea-client

### ISSUE THREAD

**Issue by stegut01** [ARMmbed/greentea#101]
In #84 we check if ```greentea-client``` is specified in 'dependencies' or 'testDependencies' but we don't check 'targetDependencies'.
See example here: https://github.com/ARMmbed/sal/blob/master/module.json

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2266

**Comment by stegut01** [comment]
```greentea-client``` should be specified in 'dependencies' or 'testDependencies'.
see PR: https://github.com/ARMmbed/sal/pull/48

**Comment by PrzemekWirkus** [comment]
We can close it, because greentea-client and utest etc. should not be in target dependencies.
