### ISSUE TITLE
No __sync response under Ubuntu 14 (64 bit)

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/greentea#104]
While using Ubuntu 14 (64 bit) we've noticed that DUT doesn't respond to ```__sync``` packet when supervised with ```mbedhtrun```.
* Manual tests (using terminal) suggest that device can correctly read data.

Tools:
* Latest greentea/htrun/mbedls/pyserial==3.0.1.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2300

**Comment by PrzemekWirkus** [comment]
I can';t reproduce this on other machines, looks like a specific linux configuration failure.
