### ISSUE TITLE
AssertionError: __main__ in multiprocessing\forking.py

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/greentea#105]
There is an occasional ```AssertionError``` on ```c:\python27\lib\multiprocessing\forking.py``` while running Greentea (actual error occurs in ```mbedhtrun```) on Windows.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "c:\python27\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
```

**Comment by PrzemekWirkus** [comment]
Will be fixed in Python 2.7.11: http://bugs.python.org/issue10128

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2314

**Comment by Hokins-Liu** [comment]
Hi PrezemekWirkus, 
How can I to fix this issue? install a new version of python?
or type upgrade command on yotta?

**Comment by PrzemekWirkus** [comment]
This was fixed in ```htrun```:
* https://github.com/ARMmbed/htrun/releases/tag/v0.2.6 and 
* https://github.com/ARMmbed/htrun/pull/74.
