### ISSUE TITLE
Docs are too dependent on K64F and Yotta

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/greentea#128]
## Problem
The docs all are very dependent on the K64F and yotta.

## Solution
Make the docs more general, add videos to liven up content. Currently its all way too dense and pigenon holed, so lets make it more general and less of a painful experience.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2577

**Comment by PrzemekWirkus** [comment]
Greentea is tool for testing code in yotta modules.
