### ISSUE TITLE
Remove dependency on mbed_target_info.py

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/greentea#131]
Currently if any platform that is tested does not exist in `mbed_target_info.py`, then you get an error: `Platform <platform> not in target info store.`

This is only used when testing yotta modules, but it is not necessary when using a test spec file. In this case, greentea should make its best effort to test all platforms.

It looks the only info it's using from the target info store in the case of a test spec file is `program_cycle_s`. Ideally we would use a different mechanism for checking to see if the platform is ready. Though for the moment I think using a sensible default would be fine.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2606

**Comment by PrzemekWirkus** [comment]
I will handle this one.

**Comment by PrzemekWirkus** [comment]
@bridadan Please have a look at #133 and review / test if it works for you.

**Comment by bridadan** [comment]
Looks good!
