### ISSUE TITLE
mbedls should warn when using old versions of Daplink

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/greentea#148]
If for some reason a user is using a platform with old firmware, then Daplink should display a warning.

A list of daplink versions should be available from the target description, for example:
https://github.com/mbedmicro/mbed/blob/master/hal/targets.json

cc @PrzemekWirkus

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2726

**Comment by PrzemekWirkus** [comment]
@mlnx I think this discussion is ongoing. People working with older repos will not have latest DAPlink version in their `targets.json` so this way can't be used. By having centralized pot with data like this we can achieve what you request here.
