### ISSUE TITLE
Doc is still about yotta tools

### ISSUE THREAD

**Issue by RdaZhongyao** [ARMmbed/greentea#176]
After mbed OS 5.1 released, test tools should be merged to it, I think.
However, this repo's doc is still about yotta, not mbed-cli.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2850

**Comment by bridadan** [comment]
@RdaZhongyao Thanks for bringing up this issue. Greentea is still compatible with yotta (in fact, it can be used with any build system now with the introduction of the [test specification file](https://github.com/ARMmbed/greentea#test-specification-json-formatted-input)), but I agree that the docs could use some updates in regards to the mbed OS 5.1 release.

cc @mazimkhan

**Comment by ivan-adzic-tridonic-com** [comment]
@daniel-cesarini-tridonic-com @markus-becker-tridonic-com this is relevant also for us.

**Comment by AnotherButler** [comment]
I believe PR #217 resolved this issue. @mazimkhan @adbridge Can you please confirm?

**Comment by mazimkhan** [comment]
Yes #217 fixes this.

**Comment by bridadan** [comment]
Should be good to close this then @mazimkhan
