### ISSUE TITLE
Trying to create html report results in error if platform or toolchain contain "-"

### ISSUE THREAD

**Issue by cuevasj** [ARMmbed/greentea#181]
Using the command **mbedgt -V --report-html=my_report.html** resulted in the attached error.

I believe the root cause is that line 599 of mbed_report_api.py splits the string platform_toolchain without setting the optional maxsplit parameter to 1.  My toolchain is frdm-k64f-gcc so the result of splitting the string (on '-') is four substrings which cannot be assigned to two variables.

When I changed the line to **platform, toolchain = platform_toolchain.split('-', 1)**, the error goes away and the html is generated.  I am very new to Python so maybe there's a better way to fix this.

![capture](https://cloud.githubusercontent.com/assets/19537551/17968809/bed066f2-6a9c-11e6-9a95-d53afa6609e4.PNG)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2871

**Comment by bridadan** [comment]
@cuevasj Is this still and issue? I see that you also reported https://github.com/ARMmbed/greentea/issues/182 so it looks like you were able to create a report. Or was that using the patch you mentioned in your comment above?

**Comment by cuevasj** [comment]
Yes, I generated the report using the patch described above.
