### ISSUE TITLE
html report file doesn't show details in a browser

### ISSUE THREAD

**Issue by cuevasj** [ARMmbed/greentea#182]
The attached (zipped) html file was generated using **mbedgt -V --report-html=my_report.html** (with the fix to mbed_report_api.py described in issue #181).

When I open the file (with Chrome, Firefox, or Internet Explorer) only OK or FAIL for each test
suite is shown.  None of the details like timing and test steps are shown, although they are actually
in the source html.  A screenshot of what I see is also attached.

It looks like clicking on OK or FAIL should result in some action, but when I do click them nothing happens.  As far as I can tell the JavaScript is not being executed.

[my_report.zip](https://github.com/ARMmbed/greentea/files/437428/my_report.zip)
![capture](https://cloud.githubusercontent.com/assets/19537551/17975839/3d06662c-6ab9-11e6-959b-d5f040873333.PNG)

**Comment by bridadan** [comment]
@cuevasj Thanks for reporting this!

I was able to create an HTML report that let me view the complete log, though that was using the mbed OS 5 release. I did notice that the JavaScript was failing to find the proper element in the attached report you posted. I made a PR that should fix this issue: https://github.com/ARMmbed/greentea/pull/183

Would mind trying that PR and seeing if it fixes your issue? Or could provide the steps that you took to create that report so I can reproduce it?

Thanks!

**Comment by cuevasj** [comment]
@bridadan You're welcome and thanks for fixing it!

Yes, the file from the PR generated a report that let me view the details - with the caveat that I had to apply the patch mentioned in #181.

For the record I'm running the mbed-drivers tests on a FRDM-K64F dev kit.  When our product is ready I'll switch to that.

**Comment by bridadan** [comment]
Great, thanks @cuevasj! We'll look into the issue you mentioned in #181 and find a proper fix, I noticed even with the patch you described some of the information got jumbled.

@mazimkhan @ConorPKeegan This patch should be ready to go!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2873

**Comment by bridadan** [comment]
@cuevasj said https://github.com/ARMmbed/greentea/pull/183 fixed this issue for him, so this should be good to close @mazimkhan @adbridge

**Comment by bridadan** [comment]
Bump, good to close @mazimkhan @adbridge
