### ISSUE TITLE
mbedgt  with multiple target: wrong platform_name

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/greentea#185]
At the end of mbedgt command, we got some test result summary

mbedgt: test case report:
+-----------------------+---------------+------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------+--------+--------+--------------------+
| target                | platform_name | test suite                                                                   | test case                                                                    | passed | failed | result | elapsed_time (sec) |
+-----------------------+---------------+------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------+--------+--------+--------------------+
| DISCO_L476VG-ARM      | DISCO_L476VG  | features-frameworks-utest-tests-unit_tests-basic_test                        | Repeating Test                                                               | 2      | 0      | OK     | 0.08               |

First target is OK, but then:

| NUCLEO_L476RG-IAR     | DISCO_L476VG  | features-frameworks-utest-tests-unit_tests-basic_test                        | features-frameworks-utest-tests-unit_tests-basic_test                        | 0      | 1      | ERROR  | 67.71              |

==>  platform_name is not correct… But maybe this issue is only typo?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2900
