### ISSUE TITLE
Memory map summary doesn't work any more

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/greentea#192]
Hi

All values are kept to 0

Ex:
Memory map breakdown for built projects (values in Bytes):
+----------------------------+---------------+-----------+------------+-------+------+-----------+-------------+
| name                       | target        | toolchain | static_ram | stack | heap | total_ram | total_flash |
+----------------------------+---------------+-----------+------------+-------+------+-----------+-------------+
| nist_internet_time_service | NUCLEO_F429ZI | ARM       |          0 |     0 |    0 |         0 |           0 |
| tcp_client_echo            | NUCLEO_F429ZI | ARM       |          0 |     0 |    0 |         0 |           0 |
| tcp_client_hello_world     | NUCLEO_F429ZI | ARM       |          0 |     0 |    0 |         0 |           0 |
| udp_echo_client            | NUCLEO_F429ZI | ARM       |          0 |     0 |    0 |         0 |           0 |
+----------------------------+---------------+-----------+------------+-------+------+-----------+-------------+

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTMORF-515

**Comment by bridadan** [comment]
@jeromecoutant I believe this should be reported to https://github.com/ARMmbed/mbed-os, since that's where the memory map script lives. Would you mind moving this issue there?

**Comment by jeromecoutant** [comment]
Hi
https://github.com/ARMmbed/mbed-os/issues/2820
