### ISSUE TITLE
Feature Request : Add ability to change UART Speed between greentea and DUT

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/greentea#196]
## Problem

It is very hard to test the UART with greentea since greentea uses the UART line. Having the ability to change the speed of the channel for testing purposes would be very useful. 
## Solution

Implemeneted in htrun and greentea-client packages "key value protocol" can be decorated with few new simple commands like {{serial_speed;115200}} etc. + some simple HAL in greentea-client to change baudrate and restart serial if needed (+ flusing some buffers?)

 I can imagine on device and host side after baudrate change request there shjould be some simple recovery so both sides for sure are transmiting in new baudrate.
 So some implementation is in order in both greentea-client (C/C++) and htrun.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTMORF-544

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by BlackstoneEngineering** [comment]
This was filled out 2 years ago before there was any formalized anything, please specify what is missing.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-40*

**Comment by BlackstoneEngineering** [comment]
@adbridge explain please?

**Comment by adbridge** [comment]
It's been moved internally into a feature request by the looks of it. This one was thus closed by Earl's team.
