### ISSUE TITLE
Retargeting does not work through mbedgt

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/greentea#202]
When retargeting a platform using the retarget functionality in mbed-ls, the retarget shows up when executing mbedls, but not when running mbedgt.
Does mbedgt call mbedls from a different working directory?

**Comment by bridadan** [comment]
Hi @stevew817, could please post the output of `pip list`? I believe this issue was patched in [mbed-ls version 1.2.1](https://github.com/ARMmbed/mbed-ls/releases/tag/v1.2.1). If you find you're using an earlier verison of mbed-ls, please run `pip install -U mbed-ls` to see if that solves your issue. Thanks!

**Comment by stevew817** [comment]
I did upgrade to latest...

pip-list:

> mbed-cli (0.9.10)
mbed-greentea (1.2.3)
mbed-host-tests (1.1.4)
mbed-ls (1.2.9)
mbed-test-wrapper (1.0.0)
mock (2.0.0)
monotonic (1.2)

**Comment by stevew817** [comment]
I think the issue is that most tools (greentea, htrun, ...) call mbedls in the following way:

> mbeds = mbed_lstools.create()
    mbeds_list = mbeds.list_mbeds_ext()

I discovered you need to specifically call retarget() on mbeds for retarget to work... So maybe the solution here is to call retarget in the create function?

**Comment by stevew817** [comment]
@bridadan The issue you referred to was for mock targets, mine is for target redirection...

**Comment by bridadan** [comment]
Oops, you're definitely right, sorry for the hasty reply!

> So maybe the solution here is to call retarget in the create function? 

I think you're right @stevew817, that seems like a good solution to me. Would you mind trying it and if it fixes your issue, submit a patch to mbed-ls?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTMORF-620

**Comment by stevew817** [comment]
@bridadan Fix PR submitted.

**Comment by bridadan** [comment]
@stevew817 Your fix has been released in the latest version of mbedls, would you mind confirming that this fixes this issue?

**Comment by bridadan** [comment]
@mazimkhan  I think that this issue is safe to close
