### ISSUE TITLE
A terminal does not print ending line causes target to be none

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/greentea#22]
mbedgt does not recognize targets in my git bash.

@PrzemekWirkus If you consider this as a bug, I would be happy, as my terminal seems to be having problems with endings.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSYST-193

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSYST-453

**Comment by PrzemekWirkus** [comment]
Fixed with https://github.com/ARMmbed/greentea/commit/2a7f26d814ddfa55afe3a9cf94c3c1e480d5e43a.
