### ISSUE TITLE
mbedgt could pass unrecognised parameters to mbedhtrun

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/greentea#229]
This would allow fine tuning of running tests without specifying target, serial port, mount point etc..

**Comment by theotherjimmy** [comment]
Yep. it could. Would you like to submit a PR to do this?

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-39*

**Comment by cmonr** [comment]
Closing since this is over a year old. If this is still an issue, please open a new issue.
