### ISSUE TITLE
Target property priority incorrect

### ISSUE THREAD

**Issue by theotherjimmy** [ARMmbed/greentea#249]
Currently we have priority as follows:
```
internal yotta blob > targets.json > tool default
```
This is a bug.

Instead the priority should be:
```
targets.json /w default > internal yotta blob > tool delaut
```

This implies a few test cases:

In targets.json        | In yotta blob | property used | Currently Works
---------------------- | ------------- | ---------------- | ---------------
Yes, with property | No            | `targets.json`   | Yes
Yes, without property| No            | default   | Yes
Yes, with property | Yes           | `targets.json`   | No
Yes, without property | Yes           | default   | No
No                     | No           | default       | Yes
No                     | Yes           | yotta blob       | Yes

@bridadan Is this the issue masked by #248?

**Comment by theotherjimmy** [comment]
@jeromecoutant @bcostm I prefer to resolve this bug over merging #248

**Comment by bridadan** [comment]
@theotherjimmy Perfect 👍

**Comment by theotherjimmy** [comment]
@bridadan Does this apply to all target properties? or just copy method?

**Comment by bridadan** [comment]
I would prefer it to be for all target properties, we shouldn't be picking and choosing from different sources.

It's currently being used for copy method and reset method

**Comment by theotherjimmy** [comment]
I updated the description and title to make it general

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTMORF-1636
