### ISSUE TITLE
Greentea doesn't have an option to set polling-timeout

### ISSUE THREAD

**Issue by juhaylinen** [ARMmbed/greentea#269]
mbedhtrun has an option for configuring polling-timeout which is missing from Greentea. It just passes the default timeout (60 s) to mbedhtrun. The timeout is not enough when flashing large image files over network and the tests cases will fail.

Please add polling-timeout to Greentea options

**Comment by theotherjimmy** [comment]
Thanks for creating this issue, so that we can track it easier.

**Comment by juhaylinen** [comment]
Thanks for the fix.

Please make a new release, so we can update Greentea to our test servers
