### ISSUE TITLE
QEMU plugin

### ISSUE THREAD

**Issue by gprossliner** [ARMmbed/greentea#276]
Hello!

How can I write a plugin to support emulated devices?

My plan would be:
1. Let green tea list and compile the tests to individual .bin files
2. If a specific test.bin file is about to run, start a QEMU session (https://gnu-mcu-eclipse.github.io/qemu/), by starting a command-line.
3. Capture the stdio from the Emulator to perform test i/o. This would be the "SerialPort".
4. If a test has completed, the qemu session is exited. There is no "reset" here, as each binary is launched in a new process.

What I basically need is to:
* Get a python method called to "flash" a binary and start the session
* Pipe stdio from the qemu session to GreenTea

How can this be accomplished?

---
Information: This is a copy of https://github.com/ARMmbed/htrun/issues/194 
Maybe this is the right place to ask.

**Comment by 0xc0170** [comment]
I'll close this one, will be answered in htrun
