### ISSUE TITLE
K64F firmware version 0226 not available

### ISSUE THREAD

**Issue by c1728p9** [ARMmbed/greentea#28]
The K64F version 0226_k20dx128_k64f_0x5000.bin is not available on mbed.org.  The latest version there is 0221.

**Comment by 0xc0170** [comment]
You mean the one referenced in the readme? 

```
Example for Freescale's FRDM-K64F platform: Please use firmware ver. 0226_k20dx128_k64f_0x5000.bin or greater.
```

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSYST-487

**Comment by PrzemekWirkus** [comment]
I've removed info about 0226 from README.md.
@c1728p9 Please release 0226 so people can actually use it on Linux.

**Comment by c1728p9** [comment]
Does greentea have problems using 0203 or 0221 on Linux?
