### ISSUE TITLE
Unit test for uart serial with greentea

### ISSUE THREAD

**Issue by sathysreenath** [ARMmbed/greentea#285]
Hi

We are using uartserial in our code and wanted to add unit tests to it, but hit a roadblock as greentea uses rawserial, is there a good way to test uart serial with greentea? Any help would be appreciated.

Thanks so much,
Sathy

**Comment by sathysreenath** [comment]
Thank you I will open the issue in mbedos.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-121*
