### ISSUE TITLE
Some cases run into SYNC_FAILED with IAR only

### ISSUE THREAD

**Issue by Ronny-Liu** [ARMmbed/greentea#287]
[IAR_report.zip](https://github.com/ARMmbed/greentea/files/2561275/IAR_report.zip)

As attached, our partner reported 15 cases experienced SYNC_FAILED, this happened only with IAR.  GCC and ARM are all 100% pass.  
Want to understand why it is toolchain specific, and not all IAR cases have this issue.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-145*

**Comment by Alex-EEE** [comment]
I'm not sure if this is related, but we are also running IAR on Windows testing on a K64 and could never get all of the test cases to pass using DAPlink, and I think it was b/c of SYNC_FAILED.  We ended up writing a J Link plugin and programmed our boards via the JTAG header, and this solved almost all of our problems.  We thought it had something to do with DAPlink failing to re mount as an external drive sometimes on Windows, but maybe it also had to do with IAR.

**Comment by Ronny-Liu** [comment]
Updated DAP from 0240 to 0251, it doesn't help.  Still, GreenTea passes all cases with ARM and GCC, but 16 SYNC ERROR among all tests.  This time one more case (tests-mbedmicro-rtos-mbed-mail) introduced SYNC Error than previous test with 0240.

**Comment by Ronny-Liu** [comment]
@bridadan tried with Mbed-os-5.11.1 again, issue was still reproduced

**Comment by bridadan** [comment]
Thanks for reproducing it again @Ronny-Liu. I don't believe I have an UNO_91H in Austin to reproduce the issue, are you running into the issue with any other board?

**Comment by Ronny-Liu** [comment]
@bridadan This is only with UNO_91H board.  We have 7 boards in UK office and i will arrange 3 for Austin.  Thanks.

**Comment by bridadan** [comment]
Thanks very much! If it is a problem with just the `UNO_91H`, that sounds like an issue with the board's port or interface firmware vs an issue with greentea. But we can still investigate a bit
