### ISSUE TITLE
Readme - dependencies section should be updated

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/greentea#31]
There are some dependencies which are not listed in setup requirements, this section: https://github.com/ARMmbed/greentea/blob/master/README.md#dependencies

There are some which are not true for this module, for instance

```
project-generator==0.5.7 (install using pip).
pyOCD (install using pip).
```

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSYST-494

**Comment by PrzemekWirkus** [comment]
Those were removed when refactoring README.
