### ISSUE TITLE
Decide on where to place mbed specific host tests

### ISSUE THREAD

**Issue by rwalton-arm** [ARMmbed/greentea#312]
In mbed-os? Near test cases that use them? Separate package? (clarify) -- Don't put mbed-specific tests into standalone greentea

**Comment by evedon** [comment]
Leave smbed specific host tests in mbed-os where they currently are

**Comment by Patater** [comment]
> Leave smbed specific host tests in mbed-os where they currently are

That's my preference as well. That might or might work when we move to using standalone greentea from Mbed OS.

**Comment by rajkan01** [comment]
The https://github.com/ARMmbed/mbed-os/pull/14755 changes updated host_test (reside inside mbed-os) to import host test framework python classes from standalone htrun. The host tests reside inside mbed-os works fine with those changes, so better to keep the host tests inside mbed-os, closing this issue
