### ISSUE TITLE
Make `mbedgt` use `mbed-tools detect --json` for device detection, to avoid needing to depend on any Python library for device detection

### ISSUE THREAD

**Issue by rwalton-arm** [ARMmbed/greentea#317]
This is only relevant if we are keeping the mbedgt (greentea-cli) command moving forward. It may be that htrun is sufficient for all use cases and we can discontinue greentea-cli.

**Comment by rajkan01** [comment]
As we decided to use htrun with CTest, this issue proposed "mbed-tools detect --json" command-line argument is no longer required, so closing this issue

**Comment by rwalton-arm** [comment]
This should still be relevant. `htrun`, CTest and CMake don't provide a way to do device detection, so we need to pass in mount point, serial port, etc... on the CMake command line. `mbedtools detect --json` would be one way of detecting the device. I don't understand the edited description to be honest, this would be _irrelevant_ if we _did_ decide to use the mbedgt command line (as that gave us a way to detect devices) but we aren't using it, so we probably need another way to detect the device.

**Comment by rajkan01** [comment]
This issue needs further clarification as CMake and CTest don't provide support for device detection.

**Comment by rajkan01** [comment]
As with the new approach greentea test htrun command run by CTest instead of mbedgt so we no longer required this proposed command-line argument and closing this issue
