### ISSUE TITLE
greentea exits with error code when no tests are found in a yotta module

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/greentea#38]
Some mbedos repos are expected to have tests in future. mbed-greentea command can not be added now or until tests exist as it returns with error code causing Jenkins job i.e. build to fail.
Hence a command line switch can be added that skipps testing if there are no tests available and exit without error.
Corresponding jira tickets is IOTSYST-583

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-593

**Comment by mazimkhan** [comment]
@PrzemekWirkus I seek input from you as you may know the historical reason for exiting with error code. Do you want to make the requested behaviour default or under a command line switch.

**Comment by mazimkhan** [comment]
As discussed with @PrzemekWirkus a yotta module should have tests in it. Hence closing the issue. We can reopen it if any use case appears in future.
