### ISSUE TITLE
greentea ignores import errors

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/greentea#45]
This code:

```Python
try:
    import mbed_lstools
    import mbed_host_tests
except:
    pass
```

https://github.com/ARMmbed/greentea/blob/master/mbed_greentea/mbed_greentea_cli.py#L47

conceals import errors and makes the real cause obscure, which results in issues like this: 
https://github.com/ARMmbed/greentea/issues/44

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-689

**Comment by PrzemekWirkus** [comment]
Yes, this is a nasty one :) Gonna take care of that :)
