### ISSUE TITLE
Feature request: Sort tests in order in list and report

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/greentea#68]
When you have many test to run, it is difficult to find the test you want in the list. Also the order of list changes between different runs which also makes it harder to find.

If the order of execution causes bugs, there is also merit for debugging in executing tests in a particular order.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-770

**Comment by PrzemekWirkus** [comment]
> When you have many test to run, it is difficult to find the test you want in the list

Can you make it more clear? Are you using ```mbedgt --list``` to list tests ?

**Comment by LiyouZhou** [comment]
When I want to run a single test, I use mbedgt --list to find the full name of the test. If I run all the test, the report comes back to say which ones failed, I will have to run the failed ones again. Sorting the list just makes the process easier.

**Comment by PrzemekWirkus** [comment]
So sorting test results by result?

**Comment by PrzemekWirkus** [comment]
I will add missing shuffle test execution order together with this issue fix.

**Comment by LiyouZhou** [comment]
I would prefer if test results are sorted by name, so that they are in the same place in every results report.

**Comment by PrzemekWirkus** [comment]
OK!

**Comment by LiyouZhou** [comment]
@PrzemekWirkus Has this been implemented?
