### ISSUE TITLE
greentea should only end a test when ^{{end}}$ is received

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/greentea#70]
Currently greentea terminates a test when ```{{end}}``` is read on stdout of mbedhtrun. Even if it is part of an error message. Like: ```HOST: Unknown test property print format: {{end}}```

Originally issue was reported on mbedhtrun https://github.com/ARMmbed/htrun/issues/44. Please this issue for steps to reproduce.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-774
