### ISSUE TITLE
Feature request: use $(yt target) as default target

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/greentea#74]
I use `mbedgt -t $(yt target)` when developing, maybe this could be the default behaviour?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-793

**Comment by PrzemekWirkus** [comment]
Hi Leo,
When you do stuff like this:
```
$ cd module
$ yt target frdm-k64f-gcc
$ mbedgt
```
Greentea will assume you meant ```mbedgt -t $(yt target)```.

So just set for yourself target first and Greentea will use it! Let me know how it went.

**Comment by LiyouZhou** [comment]
Yes this is indeed been implemented. Brilliant feature. Sorry for the stupid question. Closing issue.
