### ISSUE TITLE
Naming module and entry script is inconsistent

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/greentea#75]
I have often a problem with upgrading greentea, running it via command line or even finding this repository - recall a name which I should use. ```  pip install mbedgt/mbed-greentea/greentea/mbed-gt``` ?

repository name: greentea
module name: mbed-greentea
entry point: mbedgt

I would propose to add to entry point mbed-greentea (greentea might be too general for use?).

This might apply to htrun (its much more inconsistent there).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-797
