### ISSUE TITLE
[devel_transport] Greentea fails the test case when it is terminated at host side.

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/greentea#86]
See PR https://github.com/ARMmbed/socket-test/pull/28

The tests are failing as target do not finish the test. As it implements a forever TCP/UDP server. The tests are terminated at host side when test finishes. Tests are essentially one test in one binary/Test Suite. Greentea should be able to determine correct test result.

Solution:
host test can generate the prints that greentea parses for determining test case summary/results. Example is ```notify_complete```.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2131

**Comment by PrzemekWirkus** [comment]
That supposedly is fixed [here](https://github.com/ARMmbed/htrun/commit/a9c4998eb0f04d426c40deeb983adf866f31d225). Please check with latest greentea + htrun
