### ISSUE TITLE
Debugging is difficult with greentea-enabled tests

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/greentea#91]
I would like a way to put greentea into a mode that does not copy the test before running, ignores timeouts, etc. so that I can attach a debugger to the DUT and debug a test that interacts with a host-test.

**Comment by bridadan** [comment]
(I realize this is an old issue, just doing some clean up)

@bremoran This can be done with `mbedhtrun`, the documentation for this is here: https://docs.mbed.com/docs/mbed-os-handbook/en/latest/advanced/testing/#running-a-test-while-debugging

Do note that I don't believe this does anything to prevent host-side timeouts, so your results may vary on that.

**Comment by theotherjimmy** [comment]
Closing, as there was no response.
