### ISSUE TITLE
Support for option requirement.txt with host tests

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/greentea#92]
Host tests are written independent of greentea and htrun. They can use python packages that may not be installed on the CI slaves.
Hence host test developers should be allowed to specify their python package requirements in an optional requirement.txt file. This file can be checked in with the host test script.

**Comment by PrzemekWirkus** [comment]
Very good observation!

**Comment by PrzemekWirkus** [comment]
@mazimkhan This is still valid requirement but I think it should be satisfied by build system? Please take this under consideration Azim when developing in the future!

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by mazimkhan** [comment]
Hey @adbridge since host tests are integral to mbed-os this issue can be addressed by putting the requirements in `mbed-os/requirements.txt`. This issue could have been closed when this file was introduced.
