### ISSUE TITLE
Greentea reports host test terminated PASS test as ERROR

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/greentea#94]
See Job: http://e108747.cambridge.arm.com:8080/job/gtt/222/consoleFull
Line 
```
00:58:09 mbedgt: test suite 'socket-test-test-tcp_echo_server_v0' ............................................. OK in 70.60 sec
00:58:09 	test case: 'Waiting for incoming TCP connection' ............................................. ERROR in 0.00 sec
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2231

**Comment by PrzemekWirkus** [comment]
I can reproduce this one on my machine also.

**Comment by PrzemekWirkus** [comment]
It is reporting ERROR because it was written with utest and should not be.
See this PR to fix this: https://github.com/ARMmbed/socket-test/pull/35
