### ISSUE TITLE
Greentea ignores test count reported by utest: {{__testcase_count;8}}

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/greentea#95]
Greentea summary contains no. of tests form the test summary reported by utest. It does not include the number reported by utest in the beginning of the test suite ```{{__testcase_count;8}}```.
utest can abort test suite on a test failure. In that case the total count reported by greentea is wrong.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2230

**Comment by PrzemekWirkus** [comment]
This is a low priority for now, but we will implement this if CI flows require us to do it.

**Comment by PrzemekWirkus** [comment]
This is fixed with adding `__testcase_name` event to utest (reports all test case names at the beginning).
